name: belajar_dart_packages_application
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
publish_to: none # harus none kalo menggunakan git
dependencies:
  belajar_dart_packages_library:
    git:
      url: git@github.com:Said-Habibi/belajar_dart_packages_library.git
      ref: 1.0.0 # branch atau git
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
